### ISSUE TITLE
Error when pressing E in circle "eden_garage:getVehicles"

### ISSUE THREAD

**Issue by AGNGigaBytes** [TanguyOrtegat/esx_jb_eden_garage2#10]
When at the garage and activating the function "eden_garage:getVehicles" to get a vehicle out it returns this error

https://gyazo.com/f6f376396dadaafc4467b7d6f307759d

**Comment by TanguyOrtegat** [comment]
hmm weird, did you try to debug? do you have all required columns on your sql?

**Comment by AGNGigaBytes** [comment]
Yeh just to make sure i cleared the tables and re did them. Works fine and menu will open when there is no vehicles in your garage. Soon as you have a vehicle and you try open the menu that error will show.

**Comment by TanguyOrtegat** [comment]
delete id column and make plate primary key

**Comment by AGNGigaBytes** [comment]
https://gyazo.com/7315306059c69e3fd09e7ca8b4d68e32

Same error in f8 here

https://gyazo.com/9254ad1a69ea5c1f1ff796c3797a0487

**Comment by AGNGigaBytes** [comment]
I Fixed it man thanks

**Comment by TanguyOrtegat** [comment]
is it overall error ? or you just not did update ?

**Comment by AGNGigaBytes** [comment]
It was a error on my end, A resource of mine was conflicting with it. Although now that it is active on the server there seems to be a new problem.

Some cars are able to be removed from garage but not able to be put back in saying you can not store this vehicle. When this happened the state is not being set to 0 on that car either and you can keep removing it from the garage. No console errors

**Comment by TanguyOrtegat** [comment]
all cars should be taken from the garages and taken back into it. if you go to impound and want to get back an old vehicle that is still somewhere on the world, if will say it. if you mean not your car for entering and it is you car, there should be a mistake on your side. 

print some values and look where the error is :)

**Comment by TanguyOrtegat** [comment]
no response, closing the issue
