### ISSUE TITLE
Police Impound 

### ISSUE THREAD

**Issue by Yapadzhiev** [TanguyOrtegat/esx_jb_eden_garage2#101]
Where I have to insert this code.

if you want the impound of police and mecano to work, paste those lines when you take your duty:

exports.ft_libs:EnableArea("esx_eden_garage_area_police_mecanodeletepoint")
exports.ft_libs:EnableArea("esx_eden_garage_area_police_mecanospawnpoint")
exports.ft_libs:EnableArea("esx_eden_garage_area_Bennys_mecanodeletepoint")
exports.ft_libs:EnableArea("esx_eden_garage_area_Bennys_mecanospawnpoint")
and offduty:

exports.ft_libs:DisableArea("esx_eden_garage_area_police_mecanodeletepoint")
exports.ft_libs:DisableArea("esx_eden_garage_area_police_mecanospawnpoint")
exports.ft_libs:DisableArea("esx_eden_garage_area_Bennys_mecanodeletepoint")
exports.ft_libs:DisableArea("esx_eden_garage_area_Bennys_mecanospawnpoint")

**Comment by TanguyOrtegat** [comment]
well like it is said when you go ondutu in police job client script 
if police_wear then
--onduty
elseif citizen_wear then
--off duty
end
