### ISSUE TITLE
Parking Error

### ISSUE THREAD

**Issue by MyFacix** [TanguyOrtegat/esx_jb_eden_garage2#103]
Hi,
I have installed "esx_jb_eden_garage2", but I get error message when parking the vehicles.

_Error message : SCRIPT ERROR : Execution of native 46e571a0e20d01f1 in script host failed: Error executing native 0x46e571a0e20d01f1 at address 0x140f26454 
> fn (@ft_libs/src/trigger/trigger.client.lua:45)_

Parking out the vehicles works without any problems.
I have already test reinstalled the script as well as reinstalled "ft_libs".

Did I miss something or did I forget something ?

**Comment by NEIDER12** [comment]
Did you fixed it?
