### ISSUE TITLE
Impounds

### ISSUE THREAD

**Issue by nofacetv** [TanguyOrtegat/esx_jb_eden_garage2#104]
Where do i add these lines? do i fire them as commands or what???

exports.ft_libs:EnableArea("esx_eden_garage_area_police_mecanodeletepoint")
exports.ft_libs:EnableArea("esx_eden_garage_area_police_mecanospawnpoint")
exports.ft_libs:EnableArea("esx_eden_garage_area_Bennys_mecanodeletepoint")
exports.ft_libs:EnableArea("esx_eden_garage_area_Bennys_mecanospawnpoint")

**Comment by YoiBoiGal8xy** [comment]
No you would add those when a officer/mechanic goes on/off duty
