### ISSUE TITLE
after restart server

### ISSUE THREAD

**Issue by Blackwave78** [TanguyOrtegat/esx_jb_eden_garage2#12]
after a restart server cars are no longer in the garage and are marked as exit

**Comment by XxFri3ndlyxX** [comment]
Check in the 
for 
`-- Fonction qui change les etats sorti en rentré lors d'un restart
-- AddEventHandler('onMySQLReady', function()

	-- MySQL.Sync.execute("UPDATE owned_vehicles SET state=true WHERE state=false", {})

-- end)
-- Fin Fonction qui change les etats sorti en rentré lors d'un restart`

So it would look like 

`-- Fonction qui change les etats sorti en rentré lors d'un restart
 AddEventHandler('onMySQLReady', function()

	MySQL.Sync.execute("UPDATE owned_vehicles SET state=true WHERE state=false", {})

end)
-- Fin Fonction qui change les etats sorti en rentré lors d'un restart`

uncomment that and it should make it so on restart they go back to the garage. or use esx_jb_stopvehicledespawn so vehicle don't despawn and they they at last saved location.

**Comment by Blackwave78** [comment]
thanks
