### ISSUE TITLE
Garage detect police or ambulance vehicle purchased but

### ISSUE THREAD

**Issue by XxFri3ndlyxX** [TanguyOrtegat/esx_jb_eden_garage2#13]
So i'm not sure why but if i am a police and i buy a vehicle at the police store then store it in their garage then i go to your garage i see the vehicle name but i can't even take it out so is there a way so they don't appear in the list? Thanks!

[Database](https://i.imgur.com/O6x6dNX.png)

**Comment by TanguyOrtegat** [comment]
i do see that you have more columns then you need, you have maybe another script that interfears with the eden garage ...

**Comment by eprimex** [comment]
it's more like eden garage interferes with other scripts. This script is in no way compatible with newest esx policejob and esx vehicleshop

**Comment by TanguyOrtegat** [comment]
i must admit i don't have new scripts, but what is new ?

**Comment by TanguyOrtegat** [comment]
can i close this issue ? if no response will close it in the next days

**Comment by XxFri3ndlyxX** [comment]
yes!
