### ISSUE TITLE
An error happens on MySQL 

### ISSUE THREAD

**Issue by BeauvR** [TanguyOrtegat/esx_jb_eden_garage2#16]
When i'am trying to open the green circle i don't get a menu or error. If i try to get a vechile from the yellow circle and i click on the buy 500 i get:
`[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE owner=@identifier AND (state=false OR fourrieremecano=true) {@identifier=steam:110000113afb286}": Unknown column 'fourrieremecano' in 'where clause' `

Please help

**Comment by TanguyOrtegat** [comment]
read teh error and you will find you sollution
`Unknown column 'fourrieremecano' in 'where clause'`
