### ISSUE TITLE
Addon Car Names in Garage

### ISSUE THREAD

**Issue by Mariox6** [TanguyOrtegat/esx_jb_eden_garage2#18]
Hello,

I need help with the addon car names in the garage.
Now it shows the spawn name of the car and i want the normal name.
As example: It shows: rmodmustang and i want Ford Mustang GT.
![Need Help](https://user-images.githubusercontent.com/48855611/55170524-fe8aa280-5176-11e9-8165-3380d908de25.PNG)

**Comment by TanguyOrtegat** [comment]
just add the vehicles in vehiclenames.lua

**Comment by Mariox6** [comment]
How? And where?

**Comment by Mariox6** [comment]
What do i have to write in the vehiclenames.lua?

**Comment by SharpSabre** [comment]
> What do i have to write in the vehiclenames.lua?
This is example :

Citizen.CreateThread(function()
	-- Nissan GTR
	AddTextEntryByHash(0x9F05F101, 'Police GT 350R')
end)

**Comment by Mariox6** [comment]
How can i get the Hash?

**Comment by Mariox6** [comment]
It only shows the name when I enter the vehicle

**Comment by Mariox6** [comment]
Fixed it
