### ISSUE TITLE
Garage Bug 

### ISSUE THREAD

**Issue by DarkMatt62** [TanguyOrtegat/esx_jb_eden_garage2#19]
the garage at the end of 36 vehicles can not go out of the vehicle anymore

**Comment by TanguyOrtegat** [comment]
yes, messagepack error... make sure players do not have more then 30 vehicles (to be sure)

**Comment by DarkMatt62** [comment]
he has opportunity to fix himself problem ?

**Comment by TanguyOrtegat** [comment]
this problem is related to lua, not this sctipt, all you can do is a check in vehicleshop that people having more then 30 veicles, cannot buy more then that, they must sell some cars, in order to buy some now ones

**Comment by ElPumpo** [comment]
I think there is some sort of memory limit.. You can usally fix it by narrowing down the infofmation you display in the esx menus.

For example in esx_vehicleshop I disabled the colored money and that solved the issue for me.

**Comment by TanguyOrtegat** [comment]
> I think there is some sort of memory limit.. You can usally fix it by narrowing down the infofmation you display in the esx menus.
> 
> For example in esx_vehicleshop I disabled the colored money and that solved the issue for me.

i ll see what i can do, the thing what is taking place is the 'vehicle' column un database. wut we need to get it client sided to apply the customisation. i ll try to look for fix. But saying that, a player having more then 30 vehicles, did he buy all your vehicle shop? your economy is then not right (that's my opinion)

**Comment by ElPumpo** [comment]
I found the problem dude, here https://github.com/TanguyOrtegat/esx_jb_eden_garage2/blob/master/esx_jb_eden_garage2_cl.lua#L159

You're saving all vehicle props as the elements, which is a bad practise. That's why your menu breaks with only 30 cars, but in esx_vehicleshop we can have around 300-500 vehicles before it breaks.
