### ISSUE TITLE
When car is bought by someone, it cannot go into garage

### ISSUE THREAD

**Issue by ForthtuN** [TanguyOrtegat/esx_jb_eden_garage2#2]
So if a car is bought by a person from vehicleshop by a seller, when trying to put it into the garage it says its not possible and you need to go to the impound to get it out everytime. Also when you just bought it and if you upgrade the car it won't save when logging in the next time. I think its some sync problem with the plate number when you get the car from the seller not matching the one that garage think is your plate number. Therefor its not the same car that you take from the vehicleshop until you get it out from the impound.

**Comment by TanguyOrtegat** [comment]
when you buy the car, always put your car in garage then get it out then make modifications
do you work with new or old version of vehicleshop?

**Comment by TanguyOrtegat** [comment]
no ore responding to treat, i ll close it
