### ISSUE TITLE
Boats in car garage issue

### ISSUE THREAD

**Issue by ponduzn** [TanguyOrtegat/esx_jb_eden_garage2#20]
Im having an issue where boats show in car garages, but not in boat garages, boat garages say i dont own any boats.
There is a distinction in DB under "type", categorizing cars from boats, could you utilized that to implement a fix ?

EDIT:
seems to be related to esx_boat, not sure about a fix.

**Comment by TanguyOrtegat** [comment]
look at your sql code and the "where" in sql
