### ISSUE TITLE
Garages disappeared when trying to add another garage to vehicles 

### ISSUE THREAD

**Issue by Kevin0G** [TanguyOrtegat/esx_jb_eden_garage2#21]
Garages disappeared when trying to add another garage to vehicles, since then i have tried a fresh install. Deleting from database and completely changing the files, no garages are appearing though the mod loads with no errors on the batch

**Comment by Kevin0G** [comment]
removing cache fixed

**Comment by TanguyOrtegat** [comment]
ok, then i close the issue :)
