### ISSUE TITLE
no such entity, duplicate cars

### ISSUE THREAD

**Issue by carlosmotaa** [TanguyOrtegat/esx_jb_eden_garage2#23]
Hi! first of all thx for your script, really like it.

Idk why i can spam all vehicles i want in the yellow and green marks.
if i press f8 just cant see this, "no such entity" a lot of times. any idea? thanks!
they are mark as "rentré" all time.

**Comment by carlosmotaa** [comment]
fixed, I just had to reinstall, works great now!

**Comment by TanguyOrtegat** [comment]
ok that's cool :)  i ll close the issue :)
