### ISSUE TITLE
Do not let use it

### ISSUE THREAD

**Issue by jotikas** [TanguyOrtegat/esx_jb_eden_garage2#25]
I have added it as indicated and no grage comes out

**Comment by TanguyOrtegat** [comment]
what are you saying ?  do you use  3-3 plates ? this garage is working because it is on my main server

**Comment by jotikas** [comment]
> qué estas diciendo ? ¿Usas 3-3 platos? Este garaje está funcionando porque está en mi servidor principal.

added the sql and does not leave the garage symbol

**Comment by jotikas** [comment]
I do not know if it will be a SQL problem, I do not think so. But even the points do not appear. I could resuscitate the esx again. Thank you

**Comment by TanguyOrtegat** [comment]
i fixed bug for duping cars, but your problem is related on your server, look carefully to make all steps alright
