### ISSUE TITLE
plate? MySQL!

### ISSUE THREAD

**Issue by Matetv** [TanguyOrtegat/esx_jb_eden_garage2#26]
[31m[ERROR] [MySQL] [esx_jb_eden_garage2] An error happens on MySQL for query "SELECT * FROM owned_vehicles where plate='22OTG748' and owner='steam:1100001086e00e6'": ER_BAD_FIELD_ERROR: Unknown column 'plate' in 'where clause'[0m
In the MYSQL missing the entry "plate" or?

**Comment by TanguyOrtegat** [comment]
well thats exactly what is written :)
