### ISSUE TITLE
Doesn't despawn the old vehicle

### ISSUE THREAD

**Issue by thegambid** [TanguyOrtegat/esx_jb_eden_garage2#27]
When we get the car back from yellow circle with payment, it gives the car to the player but it doesn't despawn the old one and that causes dupe of the vehicle. Hope you help me fix that soon.

**Comment by TanguyOrtegat** [comment]
normally if you get updated code, you cannot take the car if the car is somewhere on the world

**Comment by thegambid** [comment]
> normally if you get updated code, you cannot take the car if the car is somewhere on the world

But it doesn't work correctly. What do you recommend me to do?

**Comment by TanguyOrtegat** [comment]
can you try the fixes ? thanks

**Comment by thegambid** [comment]
I've installed your latest fixes. My tests:
When I try to get the car when an another player is in it and I'm at a too far away from that garage and try to get vehicle from yellow point, it says st like "you can't take it" and doesn't give me the vehicle, but when that player gets out of my car and I try it at the same place it gives me the car but still doesn't despawn the other one. 

My question is if its not gonna work, can we disable yellow circle for good? That'd probably fix my issue.

**Comment by TanguyOrtegat** [comment]
no, if player disconnects and reconnects he can get his vehicle back

**Comment by thegambid** [comment]
Nope, this dupe works without reconnecting either.

**Comment by TanguyOrtegat** [comment]
weird, what do you do ? and what kind of plates you working with?

**Comment by thegambid** [comment]
"XXX 999" formatted plates

**Comment by TanguyOrtegat** [comment]
hmmm that's weird because i did try with spaced plates too and it is working. maybe i can debug it on your sevrer ?

**Comment by thegambid** [comment]
It'd be a great pleasure. We have a test server. How do we contact?

**Comment by TanguyOrtegat** [comment]
here is my discord: Jager Bom [dev]#2795

**Comment by TanguyOrtegat** [comment]
just UPDATE the script
