### ISSUE TITLE
i can't store a car

### ISSUE THREAD

**Issue by radiodrag** [TanguyOrtegat/esx_jb_eden_garage2#3]
Voici ce que j'ai dans la console
![image](https://user-images.githubusercontent.com/10645568/48669152-42d0ac80-eacc-11e8-8c18-a6cff0de794d.png)
Le mod cherche une colonne appelé "ID", mais ne la trouve pas, ce qui est normal car elle n'existe pas dans la base de donnée et aucun mods ne l'utilise donc elle n'est pas utilisé, mis a part par le votre. J'ai essayer de l'ajouter manuellement, mais il m'est toujours impossible de rentrer un vehicule

**Comment by TanguyOrtegat** [comment]
il faut que tu rajoute une colonne id avec auto_increment

**Comment by radiodrag** [comment]
parfait, ca fonctionne! Sinon y'a une liste des voitures qui ne peuvent pas entrer dans le garage?

**Comment by radiodrag** [comment]
oui, j'ai le ID en auto increment, mais certains véhicules refusent quand meme d'entrer au garage
![fivem_gtaprocess_2018-11-21_13-52-54](https://user-images.githubusercontent.com/10645568/48862677-0e434600-ed95-11e8-9af3-ae8aaeed5e1c.jpg)
![fivem_gtaprocess_2018-11-21_13-53-09](https://user-images.githubusercontent.com/10645568/48862678-0edbdc80-ed95-11e8-9bb7-7f598071ddea.jpg)
![mstsc_2018-11-21_13-53-51](https://user-images.githubusercontent.com/10645568/48862679-0edbdc80-ed95-11e8-9322-d2816c86e760.png)

**Comment by TanguyOrtegat** [comment]
mets des print un peu partout, voir si les valeurs sont bien envoyer

**Comment by TanguyOrtegat** [comment]
et si tu enleves le PK de plate et tu mets que id

**Comment by radiodrag** [comment]
bah comme je disais plus haut, j'ai switch pour jb_eden_garage2, j'etais pas sur cette version auparavent. tous les vehicules entrent au garage sans probleme dans cette version.
