### ISSUE TITLE
Vehicles not returning to garage on restart

### ISSUE THREAD

**Issue by Kry0n** [TanguyOrtegat/esx_jb_eden_garage2#30]
In the latest version 2 - The vehicles don't seem to go back in the garage when the server restarts.
I can pull the from the impound though. 

Anyway to get them back to garage on restart?

Thank you so much for this btw

**Comment by Kry0n** [comment]
I checked eden garage and I added this to the end of  - server.lua


AddEventHandler('onMySQLReady', function()

	MySQL.Sync.execute("UPDATE owned_vehicles SET state=true WHERE state=false", {})

end)

Vehicles are now getting flagged back to garage.

**Comment by TanguyOrtegat** [comment]
yea, thats normal i deactivated it, but like you said you can uncomment it. when they want their vehicle back they must need to go to impound to avoid ppl that wait for reboot to get their cars
