### ISSUE TITLE
Notification merge with menu

### ISSUE THREAD

**Issue by XvenDeR** [TanguyOrtegat/esx_jb_eden_garage2#33]
Hi, as title says these both things merge with each other. As in this picture:
![vgZWSBgaSe2lOHmw23GDCQ](https://user-images.githubusercontent.com/29688478/60767487-a5110880-a0c1-11e9-895e-b9d3c6317feb.png)
Any idea how to fix this?

**Comment by XvenDeR** [comment]
Also could some1 clarify this:

`if you want the impound of police and mecano to work, paste those lines when you take your duty:

exports.ft_libs:EnableArea("esx_eden_garage_area_police_mecanodeletepoint")		
exports.ft_libs:EnableArea("esx_eden_garage_area_police_mecanospawnpoint")	  		
exports.ft_libs:EnableArea("esx_eden_garage_area_Bennys_mecanodeletepoint")		
exports.ft_libs:EnableArea("esx_eden_garage_area_Bennys_mecanospawnpoint")		
and offduty:

exports.ft_libs:DisableArea("esx_eden_garage_area_police_mecanodeletepoint")		
exports.ft_libs:DisableArea("esx_eden_garage_area_police_mecanospawnpoint")	  		
exports.ft_libs:DisableArea("esx_eden_garage_area_Bennys_mecanodeletepoint")		
exports.ft_libs:DisableArea("esx_eden_garage_area_Bennys_mecanospawnpoint")		`

Where exactly put them?

**Comment by TanguyOrtegat** [comment]
> Also could some1 clarify this:
> 
> `if you want the impound of police and mecano to work, paste those lines when you take your duty:
> 
> exports.ft_libs:EnableArea("esx_eden_garage_area_police_mecanodeletepoint")
> exports.ft_libs:EnableArea("esx_eden_garage_area_police_mecanospawnpoint")
> exports.ft_libs:EnableArea("esx_eden_garage_area_Bennys_mecanodeletepoint")
> exports.ft_libs:EnableArea("esx_eden_garage_area_Bennys_mecanospawnpoint")
> and offduty:
> 
> exports.ft_libs:DisableArea("esx_eden_garage_area_police_mecanodeletepoint")
> exports.ft_libs:DisableArea("esx_eden_garage_area_police_mecanospawnpoint")
> exports.ft_libs:DisableArea("esx_eden_garage_area_Bennys_mecanodeletepoint")
> exports.ft_libs:DisableArea("esx_eden_garage_area_Bennys_mecanospawnpoint")	`
> 
> Where exactly put them?

just in client file of your job where you put on your work wear ...

i don't understand your question about the merge

**Comment by TanguyOrtegat** [comment]
[esx_jb_eden_garage2.zip](https://github.com/TanguyOrtegat/esx_jb_eden_garage2/files/3397280/esx_jb_eden_garage2.zip)
here you go, but won't push it because not nessesary
