### ISSUE TITLE
Ultra buggy. Do not use in current state.

### ISSUE THREAD

**Issue by JFosterRP** [TanguyOrtegat/esx_jb_eden_garage2#36]
3 Sep. Markers (ugly)
Terribly Optimized
You can still dupe vehicles
If you explode your vehicle nearby good luck getting it back
Too much esx_help integration (ugly)

**Comment by XvenDeR** [comment]
To get vehicle after exploding you gotta put these

```
exports.ft_libs:EnableArea("esx_eden_garage_area_police_mecanodeletepoint")
exports.ft_libs:EnableArea("esx_eden_garage_area_police_mecanospawnpoint")
exports.ft_libs:EnableArea("esx_eden_garage_area_Bennys_mecanodeletepoint")
exports.ft_libs:EnableArea("esx_eden_garage_area_Bennys_mecanospawnpoint")
```

Somewhere... that I have no idea where to be honest.

**Comment by TanguyOrtegat** [comment]
there is no dupe of vehicles
