### ISSUE TITLE
Lot of MS used

### ISSUE THREAD

**Issue by Rubylium** [TanguyOrtegat/esx_jb_eden_garage2#38]
Soo, after doing some research on my server hitch time warning, i found out that i got 2  ressource eating up my server load, and one is yours
![image](https://user-images.githubusercontent.com/19718604/62398724-c7d7f500-b579-11e9-8d0e-0b0df36cf27c.png)

**Comment by TanguyOrtegat** [comment]
you are using version 1 or 2? (thanks for reporting)

**Comment by Rubyliss** [comment]
Version 2

Le sam. 3 août 2019 à 14:54, TanguyOrtegat <notifications@github.com> a
écrit :

**Comment by Rubyliss** [comment]
i'm using version 2
And if it's not in the script by default, i didn't create any command to do thatn and if it's in the script, well i never used it befor 🤔

**Comment by TanguyOrtegat** [comment]
hmmm weird, i ll look into it when i am back from vacation

**Comment by ElPumpo** [comment]
for example @TanguyOrtegat:

https://github.com/TanguyOrtegat/esx_jb_eden_garage2/blob/master/esx_jb_eden_garage2_sv.lua#L44

you select * and use vehicle props but instead you could use the `plate` column.

**Comment by Taker54** [comment]
fixed?

**Comment by TanguyOrtegat** [comment]
> fixed?

tried to fix it, should be better now but idk if it is really fixed

**Comment by XvenDeR** [comment]
Just start ft_libs after garage, no issues that way

**Comment by Rubylium** [comment]
Forgot about this sorry.
After some search i found out that this is mainly due to SQL Sync request, exemple : MySQL.Sync.execute("UPDATE owned_vehicles SET `stored`=true WHERE `stored`=false", {})

It's way better to use Async SQL request to prevent high MS usage :)

**Comment by TanguyOrtegat** [comment]
oh great :)
