### ISSUE TITLE
Vehicle health (both engine and body)

### ISSUE THREAD

**Issue by LagMyAss** [TanguyOrtegat/esx_jb_eden_garage2#39]
In the newest es_extended, there was an update on health and body and some of the cars that are getting out of the garage, engine is broken. 

es_extended changes about vehicles:
https://github.com/ESX-Org/es_extended/commit/e850da085e694a17235501873d11635be2fa43c0
https://github.com/ESX-Org/es_extended/commit/44c05b8fae757870e3d4a37f0919da462d3d74ad

**Comment by TanguyOrtegat** [comment]
i think there must be something broken into that code, i ll send you correct code:
https://pastebin.com/vMBjYdvA
