### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by romanoff971** [TanguyOrtegat/esx_jb_eden_garage2#42]
Hi again when i approach the garage, my client crashing. Do you know why?
no error server side no error before crash
Only happen when i approach the garages.
I oppened a new one because you closed the other. 
[CitizenFX.log](https://github.com/TanguyOrtegat/esx_jb_eden_garage2/files/3487807/CitizenFX.log)

**Comment by TanguyOrtegat** [comment]
yea but garage has no prblem, your problem comes from somewhere else. otherwise everyone would crash and here only you

**Comment by XvenDeR** [comment]
Probably maps

**Comment by TanguyOrtegat** [comment]
yes ^^

**Comment by romanoff971** [comment]
i've try on a clean server, with only basics on fresh install, no maps
[CitizenFX.log](https://github.com/TanguyOrtegat/esx_jb_eden_garage2/files/3488623/CitizenFX.log)
.
same crash. here is the log :

**Comment by TanguyOrtegat** [comment]
send server too

**Comment by romanoff971** [comment]
where to take them?

**Comment by TanguyOrtegat** [comment]
into your server ...

**Comment by TanguyOrtegat** [comment]
and you got latest version?

**Comment by TanguyOrtegat** [comment]
and disable all esx scripts you have only, essentialmode and es_extended and ftlibs and basic scripts, and look if you crash

**Comment by romanoff971** [comment]
yes i have last version
already disable all esx script. here is client log :
[CfxCrashDump_2019_08_10_07_29_35.zip](https://github.com/TanguyOrtegat/esx_jb_eden_garage2/files/3488626/CfxCrashDump_2019_08_10_07_29_35.zip)
here is server log
[logfile.log](https://github.com/TanguyOrtegat/esx_jb_eden_garage2/files/3488627/logfile.log)

**Comment by TanguyOrtegat** [comment]
put you sevrer start ?

**Comment by romanoff971** [comment]
yes of course, how to log in whitout starting it? :)

**Comment by TanguyOrtegat** [comment]
copy paste lol

**Comment by romanoff971** [comment]
my server.cfg?

**Comment by romanoff971** [comment]
[server.txt](https://github.com/TanguyOrtegat/esx_jb_eden_garage2/files/3488631/server.txt)

**Comment by TanguyOrtegat** [comment]
what is your ip i come and test it
and btw:
endpoint_add_tcp "192.168.49.3:30120" 
endpoint_add_udp "192.168.49.3:30120"
you can leave both 0.0.0.0:30120 because that ip is your local ip lol

**Comment by romanoff971** [comment]
its an private server, its my test server. I can put in in a public server but i can't disable all others script...

**Comment by TanguyOrtegat** [comment]
even on you test server leace .0.0.0.0:30120

make on your sevrer a copy paste of your actual server and just chage port number
like this 0.0.0.0:30125
and start it you will have two servers running but not on same port

**Comment by romanoff971** [comment]
89.234.181.82:30125

**Comment by TanguyOrtegat** [comment]
envois ton garage que tu utilises :)

**Comment by TanguyOrtegat** [comment]
envois ton discord sera plus facile a parler

**Comment by romanoff971** [comment]
https://discord.gg/fMy92v

**Comment by TanguyOrtegat** [comment]
SOLLUTION: didn't update to latest version marker MUST be int
so 1.0 --> 1
