### ISSUE TITLE
infinite cars in green mark

### ISSUE THREAD

**Issue by lucasparri** [TanguyOrtegat/esx_jb_eden_garage2#43]
Hi, i have to say that script works really good, only thing is that i can spawn infinite cars in the green mark. What should i do to fix it?. Also make another question, do yo know how can i do to what i store in the trunk, stay there after a restart? thanks

**Comment by TanguyOrtegat** [comment]
trunk script is another script and has nothing to do with this and yes normally you keep your trunk.

Infinite cars i think you have not latest version (github) or wrong database. Check al that again and give feedback after that
