### ISSUE TITLE
#PullRequest Stock only cars

### ISSUE THREAD

**Issue by Alevhovic** [TanguyOrtegat/esx_jb_eden_garage2#44]
Hello @TanguyOrtegat,

First, thank you for all the work you've done here.

In our server, we use esx_boat (boatshop). I want to make a 'filter' on your SQL request :

sv.lua (44) :
MySQL.Async.fetchAll("SELECT * FROM owned_vehicles where plate=@plate and owner=@identifier",{['@plate'] = vehplate, ['@identifier'] = identifier}, function(result)

by

local typeCar = "car"
	MySQL.Async.fetchAll("SELECT * FROM owned_vehicles where plate=@plate and owner=@identifier and type = @typeCar",{['@plate'] = vehplate, ['@identifier'] = identifier, ['@typeCar'] = typeCar}, function(result)

but this is still showing the boats, plane etc... 

Do you have any idea ?

I'm french if you want to answer that way.

**Comment by TanguyOrtegat** [comment]
thats sql is just to check wheather that vehicle is yourse or not

**Comment by Alevhovic** [comment]
![image](https://user-images.githubusercontent.com/28044103/63381666-72814d80-c399-11e9-98de-c769be41d6fa.png)
Working fine this way ;) 

Thanks to you @TanguyOrtegat !
