### ISSUE TITLE
Making garage not working

### ISSUE THREAD

**Issue by Rubylium** [TanguyOrtegat/esx_jb_eden_garage2#45]
So after using the garage for a while i find out an bug with vehicle name that is pretty anoying, it make the garage unsuable at all.

To do this bug : 
- Open your garage
- Click the rename button on one of your vehicle
- When the window to rename is open, leave it blank and click enter or escape to remove the window

After that on the Data base the vehicle name is *Null* and the player can not open the garage anymore.

Hope this help to get it fixed ;)

**Comment by TanguyOrtegat** [comment]
thanks for your issuer will fix it soon !

**Comment by TanguyOrtegat** [comment]
issue fixed, but now before updating your garage, all null values in database must have a value

**Comment by TanguyOrtegat** [comment]
but weird thing is that vehiclename has a constraint: cannot be null
