### ISSUE TITLE
Players can spawn infinite cars

### ISSUE THREAD

**Issue by kevinalex** [TanguyOrtegat/esx_jb_eden_garage2#5]
In client.lua  line **179**

			function(data2, menu2)
					if data2.current.value == "get_vehicle_out" then
						if (data.current.value.state) then
							menu2.close()

Should add menu.close() so first menu closes after spawning a vehicle. Preventing the player from spawning multiple vehicles intentionally or accidentally.

			function(data2, menu2)
					if data2.current.value == "get_vehicle_out" then
						if (data.current.value.state) then
							menu.close()
							menu2.close()

Great script!!

**Comment by TanguyOrtegat** [comment]
thanks for participating and making the script better !
