### ISSUE TITLE
Change Blip Size ?

### ISSUE THREAD

**Issue by TarisGN** [TanguyOrtegat/esx_jb_eden_garage2#51]
Anybody know how can we change Blips size (on this resource for sure)?

**Comment by XvenDeR** [comment]
Hi.

For example
1. Open esx_jb_eden_garage2_cl.lua
2. If you want to change personal car blip find:
`							OpenMenuGarage(v, "personal", k, "car")
`
and a little below that find
`			blip = {
				text = v.Name,
				colorId = Config.Blip.color,
				imageId = Config.Blip.sprite,
			},`
3. In a blip = { section add:
`				scale = 1.0,`

So scale is the size of blip.

**Comment by TanguyOrtegat** [comment]
add this into your addarea:
`    blip = {
        text = "Exemple",
        colorId = 18,
        imageId = 51,
    },`

for example

**Comment by TanguyOrtegat** [comment]
here more details: https://fivemtools-libs.readme.io/docs/addarea

**Comment by Duqino** [comment]
Can you help me out pls. I cant figure it out 🈂️ 
Trying to change the size for all blips to 0.8

[![Screenshot from Gyazo](https://gyazo.com/8e88ab5a293d7f4efe4b57c78e78d11d/raw)](https://gyazo.com/8e88ab5a293d7f4efe4b57c78e78d11d)
[![Screenshot from Gyazo](https://gyazo.com/f06f0dcfd843476035d6f6a2d6fab4ca/raw)](https://gyazo.com/f06f0dcfd843476035d6f6a2d6fab4ca)

**Comment by TanguyOrtegat** [comment]
change scale

**Comment by Duqino** [comment]
Not sure what you mean with change scale.

I tried 0.1 and still nothing.

[![Screenshot from Gyazo](https://gyazo.com/0e869a6056c86677ac7122fa066f0e9c/raw)](https://gyazo.com/0e869a6056c86677ac7122fa066f0e9c)
[![Screenshot from Gyazo](https://gyazo.com/f2b80467a7f0d6ee553c6685185c25cf/raw)](https://gyazo.com/f2b80467a7f0d6ee553c6685185c25cf)

**Comment by TanguyOrtegat** [comment]
its not scaleId just scale

**Comment by Duqino** [comment]
Thanks works!!
