### ISSUE TITLE
I don't think it affects anything but it can be a problem

### ISSUE THREAD

**Issue by Taker54** [TanguyOrtegat/esx_jb_eden_garage2#52]
![Sin título](https://user-images.githubusercontent.com/19560107/64588657-5a528c00-d3a3-11e9-89ec-39b70c89d903.png)

¿How to fix?
:3rd_place_medal:

**Comment by TanguyOrtegat** [comment]
Hey! i don't use vertors in this script.. so you got maybe another version?

**Comment by Taker54** [comment]
This is my config.

#mysql-async
start mysql-async
start async

#essentials
add_ace resource.essentialmode command.sets allow
add_ace resource.essentialmode command.add_principal allow
add_ace resource.essentialmode command.add_ace allow
start essentialmode
start esplugin_mysql
start es_ui
start es_admin2
start es_extended
start ft_libs
start bob74_ipl
start fivem-ipl
start fivem-speedometer
start es_camera

#phone
start esx_addons_gcphone
start gcphone

#esx
start esx_menu_default
start esx_menu_dialog
start esx_menu_list
start esx_addonaccount
start skinchanger
start esx_skin
start esx_jobs
start esx_joblisting
start esx_shops
start esx_extraitems
start esx_clotheshop
start esx_atm
start esx_license
start esx_weaponshop
start esx_dmvschool
start cron
start esx_addoninventory
start esx_billing
start esx_society
start esx_vehicleshop
start instance
start esx_status
start esx_basicneeds
start esx_jb_migrate
start esx_jb_eden_garage2
start esx_jb_migrate
start esx_datastore
start esx_property
start esx_barbershop
start esx_identity
start esx_service

#jobs esx
start esx_policejob
start esx_ambulancejob
start esx_bankerjob
start esx_mechanicjob
start esx_realestateagentjob
start esx_taxijob

start esx_illegal
start esx_optionalneeds
start esx_rpchat
start esx_voice
start esx_animations
start esx_boat
start esx_boilerplate
start esx_cruisecontrol
start esx_holdup
start esx_lscustom
start esx_sit
start esx_doorlock
start esx_moneywash
start esx_nightclub
start esx_bike-rental
start esx_jb_advanced_truck_inventory
start esx_vehiclelock

**Comment by Taker54** [comment]
The police, boats and others do not work

-----------------------
USE `essentialmode`;

INSERT INTO `licenses` (`type`, `label`) VALUES
	('boat', 'Licencia Maritima')
ALTER TABLE owned_vehicles add vehicle_type varchar(10) not null default 'boat'
ALTER TABLE owned_vehicles add garage_name varchar(50) not null default 'stored'
;
----------------------

**Comment by TanguyOrtegat** [comment]
> The police, boats and others do not work
> 
> USE `essentialmode`;
> 
> ## INSERT INTO `licenses` (`type`, `label`) VALUES
> ('boat', 'Licencia Maritima')
> ALTER TABLE owned_vehicles add vehicle_type varchar(10) not null default 'boat'
> ALTER TABLE owned_vehicles add garage_name varchar(50) not null default 'stored'
> ;
there is no lisnece needed for garage script 🤔

**Comment by Taker54** [comment]
That is the sql of the boats, and it gives error. You can't buy any ship, the same goes for the police

**Comment by TanguyOrtegat** [comment]
lol no, you need to edit your sellers script to put in the table with correct information. you cannot add 2 or more default values to one column... 
look into some tutorial how to fill the database with correct values :)

**Comment by Taker54** [comment]
Can you pass it to me please, or if you can give me your discord and explain it to me a little, I will not bother you again :3

**Comment by Taker54** [comment]
Dexter#1276

**Comment by TanguyOrtegat** [comment]
an example just for you ...
`  MySQL.Async.execute(
    'INSERT INTO owned_vehicles (vehicle, owner, vehicle_type) VALUES (@vehicle, @owner, @vehicle_type)',
    {
      ['@vehicle'] = json.encode(watervehicleProps),
      ['@owner']   = xPlayer.identifier,
      ['@vehicle_type']   = "boat",
    },
    function (rowsChanged)
      TriggerClientEvent('esx:showNotification', _source, _U('watervehicle').. watervehicleProps.plate .. _('belongs'))
    end
  )`

**Comment by Taker54** [comment]
Where should i add that

**Comment by Taker54** [comment]
Thx
