### ISSUE TITLE
Where sould i add this?

### ISSUE THREAD

**Issue by Taker54** [TanguyOrtegat/esx_jb_eden_garage2#54]
it gives me mistakes with police and ambulance garages
MySQL.Async.execute( 'INSERT INTO owned_vehicles (vehicle, owner, vehicle_type) VALUES (@vehicle, @owner, @vehicle_type)', { ['@vehicle'] = json.encode(watervehicleProps), ['@owner'] = xPlayer.identifier, ['@vehicle_type'] = "boat", }, function (rowsChanged) TriggerClientEvent('esx:showNotification', _source, _U('watervehicle').. watervehicleProps.plate .. _('belongs')) end )

**Comment by Taker54** [comment]
This is my error in ambulance job.
[ERROR] [MySQL] [esx_ambulancejob] An error happens on MySQL for query "INSERT INTO owned_vehicles (owner, vehicle, plate, type, job, `stored`) VALUES ('license:667021b947339a0391023ead648a78f6d2bc1ebc', '{\"neonEnabled\":[false,false,false,false],\"modHood\":-1,\"modRoof\":-1,\"windowTint\":-1,\"modRightFender\":-1,\"modFender\":-1,\"fuelLevel\":70.0,\"modArchCover\":-1,\"plateIndex\":4,\"modWindows\":-1,\"modFrontBumper\":-1,\"modEngine\":-1,\"modDoorSpeaker\":-1,\"modHydrolic\":-1,\"dirtLevel\":5.0,\"modSpeakers\":-1,\"modFrame\":-1,\"plate\":\"UOI 9089\",\"modTrimB\":-1,\"modBrakes\":-1,\"modOrnaments\":-1,\"wheelColor\":156,\"modDashboard\":-1,\"modSpoilers\":-1,\"modVanityPlate\":-1,\"modXenon\":false,\"pearlescentColor\":112,\"modArmor\":-1,\"color2\":28,\"modStruts\":-1,\"modAerials\":-1,\"extras\":{\"1\":true},\"modEngineBlock\":-1,\"bodyHealth\":1000.0,\"engineHealth\":1000.0,\"modExhaust\":-1,\"modSmokeEnabled\":false,\"modTrunk\":-1,\"modBackWheels\":-1,\"modSeats\":-1,\"modAPlate\":-1,\"color1\":112,\"modAirFilter\":-1,\"modTank\":-1,\"modTransmission\":-1,\"modRearBumper\":-1,\"modShifterLeavers\":-1,\"modTrimA\":-1,\"model\":1171614426,\"wheels\":0,\"modPlateHolder\":-1,\"modHorns\":-1,\"tyreSmokeColor\":[255,255,255],\"modGrille\":-1,\"modSteeringWheel\":-1,\"modFrontWheels\":-1,\"modTurbo\":false,\"modSuspension\":-1,\"modDial\":-1,\"modLivery\":0,\"neonColor\":[255,0,255],\"modSideSkirt\":-1}', 'UOI 9089', 'car', 'ambulance', true)": ER_BAD_FIELD_ERROR: Unknown column 'type' in 'field list'

**Comment by Taker54** [comment]
This error in police job
[ERROR] [MySQL] [esx_vehicleshop] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE owner = 'license:0ba6f09429c2638632d61c41447883c0a0a3e63d' AND type = 'car' AND job = 'police'": ER_BAD_FIELD_ERROR: Unknown column 'type' in 'where clause'
[ERROR] [MySQL] [esx_policejob] An error happens on MySQL for query "SELECT plate FROM owned_vehicles WHERE owner = 'license:0ba6f09429c2638632d61c41447883c0a0a3e63d' AND plate = '06EGI805' AND job = 'police'": ER_BAD_FIELD_ERROR: Unknown column 'job' in 'where clause'
[ERROR] [MySQL] [esx_policejob] An error happens on MySQL for query "INSERT INTO owned_vehicles (owner, vehicle, plate, type, job, `stored`) VALUES ('license:0ba6f09429c2638632d61c41447883c0a0a3e63d', '{\"modGrille\":-1,\"neonColor\":[255,0,255],\"tyreSmokeColor\":[255,255,255],\"modTrimB\":-1,\"modStruts\":-1,\"wheelColor\":156,\"modSteeringWheel\":-1,\"modLivery\":4,\"modSuspension\":-1,\"modWindows\":-1,\"modSeats\":-1,\"pearlescentColor\":0,\"modSmokeEnabled\":false,\"modFrontBumper\":-1,\"modExhaust\":-1,\"modDashboard\":-1,\"modXenon\":false,\"plate\":\"KTO 5019\",\"modFrontWheels\":-1,\"wheels\":1,\"modBackWheels\":-1,\"modHorns\":-1,\"modOrnaments\":-1,\"fuelLevel\":65.0,\"modSpoilers\":-1,\"modHydrolic\":-1,\"modAPlate\":-1,\"modArchCover\":-1,\"modPlateHolder\":-1,\"modTrunk\":-1,\"modRightFender\":-1,\"modBrakes\":-1,\"modHood\":-1,\"model\":2046537925,\"modEngine\":-1,\"modDial\":-1,\"modAirFilter\":-1,\"modEngineBlock\":-1,\"modFender\":-1,\"modShifterLeavers\":-1,\"modVanityPlate\":-1,\"modRoof\":-1,\"modTurbo\":false,\"modSideSkirt\":-1,\"modRearBumper\":-1,\"modArmor\":-1,\"extras\":{\"1\":true,\"2\":false},\"dirtLevel\":4.0,\"color2\":134,\"color1\":134,\"modTrimA\":-1,\"plateIndex\":4,\"modTransmission\":-1,\"modFrame\":-1,\"engineHealth\":1000.0,\"modAerials\":-1,\"modDoorSpeaker\":-1,\"neonEnabled\":[false,false,false,false],\"windowTint\":-1,\"modSpeakers\":-1,\"modTank\":-1,\"bodyHealth\":1000.0}', 'KTO 5019', 'car', 'police', true)": ER_BAD_FIELD_ERROR: Unknown column 'type' in 'field list'

**Comment by Taker54** [comment]
In which file should I add everything? I think that's why I can't buy police cars nor other cars of works

ALTER TABLE `owned_vehicles` ADD INDEX `vehsowned` (`owner`);
ALTER TABLE `owned_vehicles` ADD `fourrieremecano` BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE `owned_vehicles` ADD `vehiclename` varchar(50) NOT NULL DEFAULT 'voiture';
if you want the impound of police and mecano to work, paste those lines when you take your duty:

exports.ft_libs:EnableArea("esx_eden_garage_area_police_mecanodeletepoint")
exports.ft_libs:EnableArea("esx_eden_garage_area_police_mecanospawnpoint")
exports.ft_libs:EnableArea("esx_eden_garage_area_Bennys_mecanodeletepoint")
exports.ft_libs:EnableArea("esx_eden_garage_area_Bennys_mecanospawnpoint")
and offduty:

exports.ft_libs:DisableArea("esx_eden_garage_area_police_mecanodeletepoint")
exports.ft_libs:DisableArea("esx_eden_garage_area_police_mecanospawnpoint")
exports.ft_libs:DisableArea("esx_eden_garage_area_Bennys_mecanodeletepoint")
exports.ft_libs:DisableArea("esx_eden_garage_area_Bennys_mecanospawnpoint")
#UPDATE

becasue people are not devs and they don't know how sql work ... insert these lines seperatly. look at what column you already have and which not, insert the colums you haven't:

ALTER TABLE owned_vehicle add plate varchar(50) NOT NULL;
ALTER TABLE `owned_vehicles` ADD INDEX `vehsowned` (`owner`);
ALTER TABLE `owned_vehicles` ADD `fourrieremecano` BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE `owned_vehicles` ADD `vehiclename` varchar(50) NOT NULL DEFAULT 'voiture';
and run this script once if you haven't plate column: https://github.com/TanguyOrtegat/esx_jb_migrate

with command migrate

#UPDATE 25/08

alter table owned_vehicles add vehicle_type varchar(10) not null default 'car'
alter table owned_vehicles add garage_name varchar(50) not null default 'Garage_Centre'

**Comment by TanguyOrtegat** [comment]
update script, you won't need to do anything just change sql
