### ISSUE TITLE
esx_policejob + esx_jb_eden_garage2

### ISSUE THREAD

**Issue by deviljin112** [TanguyOrtegat/esx_jb_eden_garage2#55]
If you're running esx_policejob and your garage / buy cars system doesnt work, simply add "job" column to owned_vehicles, set it to VARCHAT length of 50 or 60 and No default value. It should solve any console errors and work fine :)

**Comment by iTzCrutchie** [comment]
Thanks. Just ran into this as well and this fixed me up!

**Comment by TanguyOrtegat** [comment]
just add his 
alter table owned_vehicles add job varchar(50)
