### ISSUE TITLE
Storing vehicles

### ISSUE THREAD

**Issue by boomiiee** [TanguyOrtegat/esx_jb_eden_garage2#56]
So when i store a vehicle it saves it in the garage but when i go to the green circle to remove it. I get the notification that my vehicle is out already. after i just physically stored it at the same garage center. Not sure whats the issue but i reinstalled it about 3 - 4 and the same issue over and over any idea or fix for this?

**Comment by TanguyOrtegat** [comment]
weird, i ll have a look

**Comment by iTzCrutchie** [comment]
Figured this could help you. Seems to be a problem with the script updating mysql with the recent change from state to stored.

![image](https://user-images.githubusercontent.com/15348942/65791542-9289f680-e127-11e9-8253-1db5d2207b0e.png)

**Comment by iTzCrutchie** [comment]
I think i found where the problem lies. I modified some code on both the server and client side. Below are the changes I made and it started working. Hope this helps. I am just learning lua and programming so some of this may be wrong or not needed but wanted to update to see if it would lead you in the right direction. This is what worked for me.

esx_jb_eden_garage2_cl.lua
Changed line 79 from:
`v.state`
To:
`v.stored`

Changed line 87 from
`state = v.state`
To:
`stored = v.stored`

Changed lines 161 from 
`elseif (data.current.state) then`
To:
`elseif (data.current.stored) then`

Also changed items on the server side as I noticed a couple of states were still there.

esx_jb_eden_garage2_sv.lu

Changed lines 95-101 from:
```
RegisterServerEvent('eden_garage:modifystate')
AddEventHandler('eden_garage:modifystate', function(plate, state)
	MySQL.Async.execute("UPDATE owned_vehicles SET stored =@state WHERE plate=@plate",{
		['@state'] = state,
		['@plate'] = plate
	})
end)
```

To:
```
RegisterServerEvent('eden_garage:modifystate')
AddEventHandler('eden_garage:modifystate', function(plate, state)
	MySQL.Async.execute("UPDATE owned_vehicles SET `stored`=@stored WHERE plate=@plate",{
		['@stored'] = state,
		['@plate'] = plate
	})
end)
```

And for some reason all of a sudden it stopped trying to execute the code to change the values to stored on server restart until i made the change below also on the server side. If i didnt make this change it caused the db not to load at all. Not sure why.

Changed lines 158-164 from:
```
if Config.StoreOnServerStart then
	AddEventHandler('onMySQLReady', function()

		MySQL.Sync.execute("UPDATE owned_vehicles SET `stored`=true WHERE `stored`=false", {})

	end)
end
```

To:
```
if Config.StoreOnServerStart then
	AddEventHandler('onMySQLReady', function()

		MySQL.Sync.execute("UPDATE owned_vehicles SET stored=true WHERE stored=false", {})

	end)
end
```

**Comment by TanguyOrtegat** [comment]
> I think I found where the problem lies. I modified some code on both the server and client side. Below are the changes I made and it started working. Hope this helps. I am just learning lua and programming so some of this may be wrong or not needed but wanted to update to see if it would lead you in the right direction. This is what worked for me. I can make a pull request if that would be easier.
> 
> **esx_jb_eden_garage2_cl.lua**
> Changed line 79 from:
> `v.state`
> To:
> `v.stored`
> 
> Changed line 87 from
> `state = v.state`
> To:
> `stored = v.stored`
> 
> Changed lines 161 from
> `elseif (data.current.state) then`
> To:
> `elseif (data.current.stored) then`
> 
> Also changed items on the server side as I noticed a couple of states were still there.
> 
> **esx_jb_eden_garage2_sv.lu**
> 
> Changed lines 95-101 from:
> 
> ```
> RegisterServerEvent('eden_garage:modifystate')
> AddEventHandler('eden_garage:modifystate', function(plate, state)
> 	MySQL.Async.execute("UPDATE owned_vehicles SET stored =@state WHERE plate=@plate",{
> 		['@state'] = state,
> 		['@plate'] = plate
> 	})
> end)
> ```
> 
> To:
> 
> ```
> RegisterServerEvent('eden_garage:modifystate')
> AddEventHandler('eden_garage:modifystate', function(plate, state)
> 	MySQL.Async.execute("UPDATE owned_vehicles SET `stored`=@stored WHERE plate=@plate",{
> 		['@stored'] = state,
> 		['@plate'] = plate
> 	})
> end)
> ```
> 
> And for some reason all of a sudden it stopped trying to execute the code to change the values to stored on server restart until I made the change below also on the server side. If I didn't make this change it caused the db not to load at all on server restarts, breaking all the other scripts that used the db. Not sure why.
> 
> Changed lines 158-164 from:
> 
> ```
> if Config.StoreOnServerStart then
> 	AddEventHandler('onMySQLReady', function()
> 
> 		MySQL.Sync.execute("UPDATE owned_vehicles SET `stored`=true WHERE `stored`=false", {})
> 
> 	end)
> end
> ```
> 
> To:
> 
> ```
> if Config.StoreOnServerStart then
> 	AddEventHandler('onMySQLReady', function()
> 
> 		MySQL.Sync.execute("UPDATE owned_vehicles SET stored=true WHERE stored=false", {})
> 
> 	end)
> end
> ```
> 
> Again just learning lua myself and this is what worked for me. It may be wrong and ugly but wanted to share. Thanks for the awesome script by the way! :)

ooh yea you are the hero ofc we need to change client side too, completely forgot it...

**Comment by TanguyOrtegat** [comment]
the thin is i think stored is a variable that is fixed in bd, you cannot use it as variable, only with ''
