### ISSUE TITLE
Can't store Aircrafts in the garage.

### ISSUE THREAD

**Issue by DennisFusha** [TanguyOrtegat/esx_jb_eden_garage2#57]
When I buy an Aircraft and try to store it at the airport garage it says,

Can't store this vehicle.

Fix someone?

**Comment by iTzCrutchie** [comment]
Do you get any console or server errors? And is their a database entry for the plane that says you own it? 

I haven't had this issue but can test tomorrow.

**Comment by DennisFusha** [comment]
> Do you get any console or server errors? And is their a database entry for the plane that says you own it?
> 
> I haven't had this issue but can test tomorrow.

I fixed this myself in the client script.

**Comment by SilentPain96** [comment]
how did you fix that same problem

**Comment by iTzCrutchie** [comment]
Depends on the s riot you are using. My aircraft shop was calling the plane a plane in the dB instead of aircraft. Had to fix it in that script.

**Comment by TanguyOrtegat** [comment]
> Depends on the s riot you are using. My aircraft shop was calling the plane a plane in the dB instead of aircraft. Had to fix it in that script.

indeed, will have to fix that and add a heli spawnpoint becasue esx is doing its own thing and not looking at what others made before making changes
