### ISSUE TITLE
Decoding all vehicles server side?!

### ISSUE THREAD

**Issue by ElPumpo** [TanguyOrtegat/esx_jb_eden_garage2#6]
https://github.com/TanguyOrtegat/esx_jb_eden_garage2/blob/4ed6b5e44f3b45b26043830f61aa774484e16538/esx_jb_eden_garage2_sv.lua#L35

You should let the client decode the vehicle props and not the server, to save performance.

**Comment by samuelds** [comment]
or no use json :D

**Comment by TanguyOrtegat** [comment]
solved just need to do encode too :) thanks
