### ISSUE TITLE
Error MY SQL

### ISSUE THREAD

**Issue by Borkisch** [TanguyOrtegat/esx_jb_eden_garage2#60]
[ERROR] [MySQL] [esx_jb_eden_garage2] An error happens on MySQL for query "UPDATE owned_vehicles SET state =true WHERE plate='XWY 439'": ER_BAD_FIELD_ERROR: Unknown column 'state' in 'field list' 

Can somebody help me to fix this error because when i try to store my vehicle it says this in the console . I can't find a solution

**Comment by iTzCrutchie** [comment]
It says it right there. It can't find the state column in your mysql database. Did you import the eden_garage sql as well? Be sure to import both owned vehicles and eden garage sqls either in fr or en. So you would import for examples owned_vehicles_en AND eden_garage_en

 Probably should merge the two sqls so we don't have to import two sqls would make it easier.

**Comment by iTzCrutchie** [comment]
Are you using the latest version? It shouldn't be looking for the state column anymore and just be looking for stored.

**Comment by TanguyOrtegat** [comment]
> Are you using the latest version? It shouldn't be looking for the state column anymore and just be looking for stored.

indeed

**Comment by TobiClaraPA** [comment]
https://youtu.be/Vm2Qjvibjmk
