### ISSUE TITLE
Still Cant duplate car

### ISSUE THREAD

**Issue by dwiprizzy** [TanguyOrtegat/esx_jb_eden_garage2#61]
hi i have some issue with this scripft, the impound car still can be duplate if the player relogin into  server. can u fix it ? or how to fix it ?

**Comment by TanguyOrtegat** [comment]
Cant be fixed unfortunately... relogging is the only thing for dupe ...

**Comment by dwiprizzy** [comment]
hi @TanguyOrtegat  hi is that possible make take car from impound they must pay 20% from vehicle price? can anyone share the code ?

**Comment by TanguyOrtegat** [comment]
Yes possible
