### ISSUE TITLE
vehiclename problem in owned_vehicle table

### ISSUE THREAD

**Issue by NitroX28** [TanguyOrtegat/esx_jb_eden_garage2#63]
Hi, i have a problem with your ressource, when somebody buy a car in the shop , in the DB the column vehiclename stay at 'voiture' so when we go take the car in the garage , it's written 'voiture' and not ,for example, 'Audi RS6' so if you could help it's would be great 

i use the esx_vehiculeshop 

![fghjbfdgdfbg](https://user-images.githubusercontent.com/60326025/73140619-36a29080-407b-11ea-9ef7-d0c0ac59db1a.png)

**Comment by TanguyOrtegat** [comment]
change https://github.com/TanguyOrtegat/esx_jb_eden_garage2/blob/master/client/main.lua#L71 

vehicle to voiture

**Comment by NitroX28** [comment]
nothing change , it's always write voiture

**Comment by TanguyOrtegat** [comment]
this line too
https://github.com/TanguyOrtegat/esx_jb_eden_garage2/blob/master/client/main.lua#L370

**Comment by NitroX28** [comment]
Ok so it's working but when players buy a car they need to go in the garage to change the car name , if not it will be write voiture , so it is normal or not ? 

And also i have only try with add-ons so did you think it's the problem ?

**Comment by TanguyOrtegat** [comment]
fixed this now too
