### ISSUE TITLE
when i try to get the vehicle into the garage it says cant store vehicle im buying it from the vehicleshop

### ISSUE THREAD

**Issue by analski** [TanguyOrtegat/esx_jb_eden_garage2#65]

**Comment by Xaroc2** [comment]
Have the same problem = (

**Comment by TanguyOrtegat** [comment]
can you show me database ? 
maybe make a video of the database with gameplay tha you cannot entre vehicle

**Comment by TobiClaraPA** [comment]
https://youtu.be/Vm2Qjvibjmk

**Comment by TanguyOrtegat** [comment]
i have fixed it for version 1.2.0
