### ISSUE TITLE
society exited vehicles can be dupllicated

### ISSUE THREAD

**Issue by Ry80X** [TanguyOrtegat/esx_jb_eden_garage2#66]
If an member of society take out a car, another member can go to recovery and get the car back duplicating it

**Comment by TanguyOrtegat** [comment]
indeed, unfortunatly... the vehicles are dsaved on client side.. Didn't fine any sollution to get it done server sided. Maybe yoou got any sollution?

**Comment by TanguyOrtegat** [comment]
tried it again?
