### ISSUE TITLE
Cannot store vehicle, the resource does not seem to know that I own vehicles?

### ISSUE THREAD

**Issue by heyheyitsmeman** [TanguyOrtegat/esx_jb_eden_garage2#68]
I am using the latest and original esx_vehicleshop, the database is alright, and no errors in console.

Any help?

**Comment by TobiClaraPA** [comment]
Hello, you have to have ft_libs under esx_edengarage2
https://cdn.discordapp.com/attachments/555222024025276416/695411217983864872/thisordeer.png

**Comment by TobiClaraPA** [comment]
https://youtu.be/Vm2Qjvibjmk

**Comment by TanguyOrtegat** [comment]
you have the correct sql ?

**Comment by TanguyOrtegat** [comment]
fixed with extended 1.2.0
