### ISSUE TITLE
Error stock vehicle

### ISSUE THREAD

**Issue by LilEligius** [TanguyOrtegat/esx_jb_eden_garage2#7]
![image](https://user-images.githubusercontent.com/46383847/50915730-b7272c80-1439-11e9-9132-06b31961b61c.png)

**Comment by LilEligius** [comment]
![image](https://user-images.githubusercontent.com/46383847/50915815-e2118080-1439-11e9-8fcc-803d16d9ee71.png)

**Comment by TanguyOrtegat** [comment]
you did update all sql , show me your sql :)

**Comment by TanguyOrtegat** [comment]
try with new version :)

**Comment by TanguyOrtegat** [comment]
normaly it is fixed. open new issue if it isn't
