### ISSUE TITLE
This vehicle cannot be stored

### ISSUE THREAD

**Issue by TobiClaraPA** [TanguyOrtegat/esx_jb_eden_garage2#72]
I bought a car, I went to the garage, I tried to save it and it tells me that it is not possible to save it, I have the perfect sql, I have the ft_libs under the script, I don't know what else it could be, the only difference is that I am with ESX master
https://youtu.be/Vm2Qjvibjmk

**Comment by TanguyOrtegat** [comment]
errors server sided ?
how does your database look when buying a car ?

**Comment by TobiClaraPA** [comment]
![toma](https://user-images.githubusercontent.com/55306209/78579661-a4033800-7807-11ea-9707-00d7b20e1dfd.png)

**Comment by TobiClaraPA** [comment]
Here is my database

**Comment by TobiClaraPA** [comment]
No solution
