### ISSUE TITLE
I can't store my vehicle? 

### ISSUE THREAD

**Issue by rxbindotmp3** [TanguyOrtegat/esx_jb_eden_garage2#73]
Hey i don't understand why :/
![unnamed](https://user-images.githubusercontent.com/53920485/78412245-f29bb100-7612-11ea-8c65-c2cb37c89db9.jpg)
![1](https://user-images.githubusercontent.com/53920485/78412259-ffb8a000-7612-11ea-9402-9b71b4936db6.PNG)
![12](https://user-images.githubusercontent.com/53920485/78412261-021afa00-7613-11ea-82f1-a0637a5e2ac3.PNG)

**Comment by TobiClaraPA** [comment]
https://youtu.be/Vm2Qjvibjmk

**Comment by rxbindotmp3** [comment]
I have that problem!

**Comment by TanguyOrtegat** [comment]
i ll look at it tonight

**Comment by TanguyOrtegat** [comment]
just tried it on my local server and everything is working ... you inserted my sql ?

**Comment by TanguyOrtegat** [comment]
becasue you have 7 columns i do have 8

**Comment by TobiClaraPA** [comment]
![toma](https://user-images.githubusercontent.com/55306209/78579548-7cac6b00-7807-11ea-9683-c0e08c479481.png)

**Comment by TanguyOrtegat** [comment]
@TobiClaraPA  can you try an 8 alfanumeric plate ? (meaning with no spaces, in total 8 letters and numbers)

**Comment by TobiClaraPA** [comment]
Which column?

**Comment by TanguyOrtegat** [comment]
change plate to: AAAAAAAA
and change in vehicle plate: "AAAAAAAA"

**Comment by TobiClaraPA** [comment]
![asi](https://user-images.githubusercontent.com/55306209/78580990-a36ba100-7809-11ea-8c8d-030b1f9fdac1.png)

**Comment by TanguyOrtegat** [comment]
yes but your vehicle column got only 2 things, it needs more, just keep original things and change plate

**Comment by TobiClaraPA** [comment]
Do you have discord or something to talk privately?

**Comment by TanguyOrtegat** [comment]
> Do you have discord or something to talk privately?

insert this in vehicle

`{"modDial":-1,"modSideSkirt":-1,"neonColor":[255,0,255],"fuelLevel":65.0,"modAerials":-1,"modTrimA":-1,"modPlateHolder":-1,"plateIndex":0,"modelName":"COGCABRI","modHorns":-1,"wheelColor":156,"modFrontWheels":-1,"modExhaust":-1,"modTurbo":false,"modBackWheels":-1,"modAirFilter":-1,"modArmor":-1,"modArchCover":-1,"modSpoilers":-1,"modTransmission":-1,"modXenon":false,"modSeats":-1,"modEngine":-1,"modStruts":-1,"modWindows":-1,"modRoof":-1,"modSuspension":-1,"modSpeakers":-1,"modTrunk":-1,"windowTint":-1,"modFrontBumper":-1,"tyreSmokeColor":[255,255,255],"bodyHealth":1000.0,"modVanityPlate":-1,"modEngineBlock":-1,"modHydrolic":-1,"modSteeringWheel":-1,"wheels":0,"dirtLevel":8.1273345947266,"modFender":-1,"modTank":-1,"modRightFender":-1,"modHood":-1,"pearlescentColor":24,"modShifterLeavers":-1,"modFrame":-1,"engineHealth":1000.0,"modDoorSpeaker":-1,"modAPlate":-1,"modTrimB":-1,"color1":2,"color2":1,"model":330661258,"plate":"AAAAAAAA","modRearBumper":-1,"modSmokeEnabled":false,"modGrille":-1,"modLivery":-1,"modOrnaments":-1,"modBrakes":-1,"modDashboard":-1,"neonEnabled":[false,false,false,false],"health":1000}`

**Comment by TobiClaraPA** [comment]
I just deleted the owned_vehicles and install your owned_vehicles

**Comment by TanguyOrtegat** [comment]
yes, and downloaded updated script too

**Comment by TobiClaraPA** [comment]
![pro](https://user-images.githubusercontent.com/55306209/78582122-30632a00-780b-11ea-980a-35a071425434.png)

**Comment by TobiClaraPA** [comment]
Done, installed the latest version and your sql, now I have to test

**Comment by TobiClaraPA** [comment]
![otra](https://user-images.githubusercontent.com/55306209/78582411-9a7bcf00-780b-11ea-820e-dbc76a0c66dd.png)

**Comment by TobiClaraPA** [comment]
Buy another vehicle and nothing, try to get a vehicle and nothing

**Comment by TanguyOrtegat** [comment]
any errors client / server sided ?

**Comment by TanguyOrtegat** [comment]
add me on discord

**Comment by TobiClaraPA** [comment]
Okay, there I add you, regarding the errors, not any errors, now I am returning the server, with all the scripts in master version to see what happens

**Comment by TobiClaraPA** [comment]
Ready sent request

**Comment by TanguyOrtegat** [comment]
accepted, but if no errors i can't really help, becasue installed fram scratch new vehicleshop and eden garage2 and everything works great

**Comment by TanguyOrtegat** [comment]
fixed
