### ISSUE TITLE
problem with policejob and eden_garage 2

### ISSUE THREAD

**Issue by zoomlordir** [TanguyOrtegat/esx_jb_eden_garage2#74]
hi i can buy a car from policejob and when i change my job still can exit a police car from garage 
my sql just fine and have column job in my sql owned_vehicles
how can i fixed it?

**Comment by TanguyOrtegat** [comment]
in my garages owner must be police

**Comment by TanguyOrtegat** [comment]
is that okay ?

**Comment by zoomlordir** [comment]
sorry when you close the issues a notification will be sent to me
can you explain more than that i don't understand

**Comment by zoomlordir** [comment]
oo yea into the database jobs set to police yea jobs working but player still can bring out the police car

**Comment by TanguyOrtegat** [comment]
> oo yea into the database jobs set to police yea jobs working but player still can bring out the police car
> ((player job changed to other jobs))

In thé owner column put the job name

**Comment by FBFezz** [comment]
My owner column has the job name but I can still take it out when I'm not that job from the garage
