### ISSUE TITLE
REQUEST: Add fuel save, and more damage car save!

### ISSUE THREAD

**Issue by Tinky124** [TanguyOrtegat/esx_jb_eden_garage2#77]

**Comment by TanguyOrtegat** [comment]
fuel save is already in vehicleprops and damage save too. So idk what you want more

**Comment by Tinky124** [comment]
@TanguyOrtegat ok damage is good very nice bro, but fuel random goes out so it doesnt save good when i put car with fuel of 22 i get car with 67 fuel.. Look at video:https://streamable.com/mwo04x

I am using LegacyFuel

**Comment by TanguyOrtegat** [comment]
Yes it is your script legacyfuel causing that.

**Comment by Tinky124** [comment]
@TanguyOrtegat Ok dude thanks <3 <3 i will ask developer also i like news update and keep with good work
