### ISSUE TITLE
REQUEST: Headlight

### ISSUE THREAD

**Issue by NitroX28** [TanguyOrtegat/esx_jb_eden_garage2#78]
Hi dude, i want to know if it's possible to save headlights color and also , there is an issue i have made , it was the 63 and i always have the problem , when somebody buy a car , the car will have the good name in the menu but in the DB it's written "voiture" and i have donc changes you have say in the issue 63 but nothing happen , please can you help me man ? :)

**Comment by TanguyOrtegat** [comment]
install new database and add new scritp will work fine. Saving headlight ? i can look into it

**Comment by NitroX28** [comment]
Sorry it's not written "voiture" but "NULL" and ok tell me if you have something for headlights 😉

**Comment by TanguyOrtegat** [comment]
> Sorry it's not written "voiture" but "NULL" and ok tell me if you have something for headlights 😉

null is new version yes

**Comment by TanguyOrtegat** [comment]
headlight color is pushed

**Comment by NitroX28** [comment]
ok so did it's change the sql files ?

**Comment by TanguyOrtegat** [comment]
no

**Comment by TanguyOrtegat** [comment]
solved ?
