### ISSUE TITLE
Duty problem

### ISSUE THREAD

**Issue by snakezdigital** [TanguyOrtegat/esx_jb_eden_garage2#79]
This is not an error but i would like to know what is the duty you use because i use esx_duty and i dont know how to add the line for police and mechanic impound

**Comment by YisusTM01** [comment]
Just when police detects your job is police.

**Comment by TanguyOrtegat** [comment]
i have just in my policejob if sitizen wear then not on duty, if work wear then he is on duty

**Comment by snakezdigital** [comment]
so where should i add the impound line ? in policejob or in esx_duty

**Comment by TanguyOrtegat** [comment]
i have litterly told you where to put it in comment above
