### ISSUE TITLE
Even if my boat is in "owned vehicles" can't store it 

### ISSUE THREAD

**Issue by MarcoBaratti** [TanguyOrtegat/esx_jb_eden_garage2#80]
Hello

I have the esx_boatshop and i tried to edit the server main to make boats go into owned vehicles. It's working but still can't store them into the boat garage

**Comment by TanguyOrtegat** [comment]
you dont need any ohter garage script then this. Boat garage is already included in this script. Jus make type = "boat"

**Comment by TanguyOrtegat** [comment]
oh thats weird will look into it when i got time

**Comment by TanguyOrtegat** [comment]
still having that issue ?

**Comment by Tinky124** [comment]
No response, close issuse @TanguyOrtegat
