### ISSUE TITLE
Can not store this vehicle

### ISSUE THREAD

**Issue by Soviet1994** [TanguyOrtegat/esx_jb_eden_garage2#83]
When I go to store the vehicle it gives me this https://i.imgur.com/qS6kx9G.jpg. I checked my database and https://i.imgur.com/EJoBTan.png is what Im seeing? Why is this? Script im using with this is esx_aircraftshop. Thanks!

**Comment by TanguyOrtegat** [comment]
give me more explanaions because i don't understand what your problem is and i cannot even see your whole database

**Comment by SanderAli** [comment]
> dame más explicaciones porque no entiendo cuál es tu problema y ni siquiera puedo ver toda tu base de datos

You may not have followed the instructions. I have tested the entire garage system and it works. Great job @TanguyOrtegat

**Comment by TanguyOrtegat** [comment]
> > dame más explicaciones porque no entiendo cuál es tu problema y ni siquiera puedo ver toda tu base de datos
> 
> You may not have followed the instructions. I have tested the entire garage system and it works. Great job @TanguyOrtegat

thanks <3
