### ISSUE TITLE
I get an error

### ISSUE THREAD

**Issue by SAYREXx** [TanguyOrtegat/esx_jb_eden_garage2#87]
I get an error
https://i.imgur.com/W1eaNqV.png

**Comment by TanguyOrtegat** [comment]
You are sure you have correct database ? because it's like it doesn't save your vehicle correctly
Maybe show a video when buying the vehicle/ database / the garage

**Comment by SAYREXx** [comment]
> You are sure you have correct database ? because it's like it doesn't save your vehicle correctly
> Maybe show a video when buying the vehicle/ database / the garage

I think I fixed it. What is the yellow marker for?

**Comment by TanguyOrtegat** [comment]
try it and you ll see, its impound
