### ISSUE TITLE
Being able to change marker type without losing access

### ISSUE THREAD

**Issue by TheRealDadbeard** [TanguyOrtegat/esx_jb_eden_garage2#88]
So I wanted to change the type of marker but ft_libs does not seem to support changing it or I'm blind.

But manually changing the type in code just stretches it and after correcting it via config make the hotspot to small to activate.

Any ideas what I could do?

**Comment by TanguyOrtegat** [comment]
hi, ft_libs does support changing markers.
change marker type over here https://github.com/TanguyOrtegat/esx_jb_eden_garage2/blob/master/client/main.lua#L571

**Comment by TheRealDadbeard** [comment]
Thats what I changed too but the issue is if you change the type to the car symbol you need to change the weight to a smaller number so that it's not massive but then the hotspot to activate it is so small that it doesn't trigger at all.

**Comment by TanguyOrtegat** [comment]
put here weight something else
https://github.com/TanguyOrtegat/esx_jb_eden_garage2/blob/master/client/main.lua#L574
